name: bli
channels:
  - defaults
dependencies:
  - python=3.7
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - ncurses
  - openssl
  - pip
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib